name: location_context
description: Helper widgets to share location data using InheritedWidgets
version: 1.0.0
author: Brian Armstrong <brian@flutter.institute>
homepage: https://flutter.institute/

dependencies:
  flutter:
    sdk: flutter
  location: 1.3.4
  quiver: "^0.29.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: "^2.0.7"

flutter:
  uses-material-design: true
